spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: db12345

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        jdbc.batch_size: 250
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
